#!/usr/bin/env python2.7

import pygame

try:
    pygame.init()

    display = pygame.display.set_mode((320, 240), pygame.FULLSCREEN)
    pygame.display.set_caption("BZCheatFree")

    clock = pygame.time.Clock()

    while True:
        clock.tick(10)

        for e in pygame.event.get():
            if e.type == pygame.QUIT:
                quit(0)
            elif e.type == pygame.VIDEORESIZE:
                display = pygame.display.set_mode((e.size[0], e.size[1]), pygame.RESIZABLE)
                surf = pygame.display.get_surface()
                surf.fill((0, 0, 0)) # black. no more visibility cheats, yay!
        
finally:
    pygame.quit()
